### PR TITLE
fix: operands order in `le` and `lt` `Felt` op bindings

### LINKED ISSUE #175: Missing integration (semantic) tests for comparison ops for Felt intrinsics
Due to the missing comparison ops implementation for the Rust `Felt` type.

### LINKED ISSUE #868: Check `lt` and `gt` felt ops
Mentioned elsewhere:

> `lt` and `gt` operator doesn't give correct output , I used  `.as_u64()` over the felt to resolve this
> ```rust
>     {
>         // Validate input: input_amount must not exceed requested_asset_total
>         let is_valid = if total_input_amount <= requested_asset_total {
>             felt!(1)
>         } else {
>             felt!(0)
>         };
> 
>         assert_eq(is_valid, felt!(1));
>     }
> ```

### PR DESCRIPTION
**Pull request by greenhat**
Close #868 
Close #175

### CODE REVIEW

File: sdk/field/src/wasm32.rs [hunk 1]
```diff
@@ -255,12 +255,12 @@ impl PartialOrd for Felt {
 
     #[inline(always)]
     fn lt(&self, other: &Self) -> bool {
-        unsafe { extern_lt(*other, *self) != 0 }
+        unsafe { extern_lt(*self, *other) != 0 }
```
Comment (bitwalker) [inline sdk/field/src/wasm32.rs:258]: Ah, I see, we were reversing the operand order in the Rust bindings, but since the compiler already does the reversal, we ended up with the operands in the wrong order. Good catch!

**Review by bitwalker — APPROVED** [review]
