### PR TITLE
Fix a bug in `mem::store_sw` intrinsic which used incorrect masks in unaligned writes.

### LINKED ISSUE #719: Add tests for unaligned writes using the `mem::store_dw` intrinsic.
See the tests in #718 and replicate for `mem::store_dw`.

### PR DESCRIPTION
**Pull request by otrho**
`mem::store_dw` is probably similarly broken, I haven't checked.

Closes #719.

### CODE REVIEW

**Comment by otrho** [comment]
Ugh, typo in the commit message. :facepalm:

File: tests/integration/src/codegen/intrinsics/mem.rs [hunk 1]
```diff
@@ -731,3 +731,99 @@ fn store_u8() {
...
+        // Return a constant to satisfy test infrastructure
+        let result = builder.u32(1, SourceSpan::default());
+        builder.ret(Some(result), SourceSpan::default()).unwrap();
+    });
+
+    fn run_test(
+        package: &miden_mast_package::Package,
+        context: &std::rc::Rc<midenc_hir::Context>,
+        write_to: u32,
+        idx: u32,
```
Comment (greenhat) [inline tests/integration/src/codegen/intrinsics/mem.rs]: `idx` -> "offset"? Also, the first three arguments can be removed since we're passing the same values on every call.

**Comment by greenhat** [comment]
> `mem::store_dw` is probably similarly broken, I haven't checked.

Yeah, that might be the case. Worth checking out.

File: tests/integration/src/codegen/intrinsics/mem.rs (hunk 1 above)
Comment (otrho) [reply tests/integration/src/codegen/intrinsics/mem.rs]: I made `run_test` a function (hence requiring those args to be passed) because I assumed there'd be some borrowing conflicts if it was a closure.  But a quick check says that `run_test` can be a closure afterall.  OK.
