### PR TITLE
[1/x] Update VM with the absolute paths support

### LINKED ISSUE #211: Assembler fails to parse emitted `mem::intrinsics::*` calls
After I drafted the solution for #207 the next error popped up. 
Emitted `mem::intrinsics::*` calls fail to be parsed by the assembler with the error:
```
  x invalid syntax
    ,-[user_ns::abi_transform_tx_kernel_get_inputs:47:25]
 46 |     u32div.16
 47 |     exec.intrinsics::mem::load_sw
    :                         ^|
    :                          `-- found a :: here
 48 |     push.2
    `----
  help: expected primitive opcode (e.g. "add"), or "end", or control flow
        opcode (e.g. "if.true")
```

I think we should import them with `use.intrinsics::mem` first and then call with `exec.mem::load_sw`.

### PR DESCRIPTION
**Pull request by greenhat**
Close #211

### CODE REVIEW

File: codegen/masm/src/emulator/mod.rs [hunk 1]
```diff
@@ -1547,6 +1549,19 @@ impl Emulator {
                     return Ok(EmulatorEvent::EnterLoop(body_blk));
                 }
                 Op::Exec(callee) => {
+                    // remove the `::` prefix (absolute path) if any from the
```
Comment (greenhat) [inline codegen/masm/src/emulator/mod.rs:1552]: @bitwalker I've tried to find anything resembling the invocation infra from the VM in the emulator to properly implement absolute paths but did not find any. I put a quick and dirty workaround stripping the `::` prefix.

**Comment by bitwalker** [comment]
FYI - the absolute paths PR was merged, so we can switch away from my branch to `next`

File: codegen/masm/src/emulator/mod.rs (hunk 1 above)
Comment (bitwalker) [reply codegen/masm/src/emulator/mod.rs:1552]: We may need to extend our representation a bit, in order to allow importing MASM modules from source. In particular, we may want to have a variant of `FunctionIdent` called `Callee` used in our MASM representation, like so:

```rust
pub enum Callee {
    MastRoot(RpoDigest),
    Path {
        module: Option<Ident>,
        function: Ident,
        absolute: bool,
    }
}
```

When translating HIR `FunctionIdent` to `Callee`, it would become  a path where the `module` would always be set, and `absolute` would always be `true` (since function identifiers in HIR are always absolute).

When translating MASM `InvocationTarget` to `Callee`, we'd convert `InvocationTarget::AbsolutePath` as an absolute callee, `InvocationTarget::ProcedurePath` as a relative path, `InvocationTarget::ProcedureName` as a relative path, and `InvocationTarget::MastRoot`, as a MAST root. Similar translations could be supported for other `InvocationTarget`-like procedure identifiers, but the MASM opcodes only use `InvocationTarget`.

The emulator then would need to resolve relative paths at runtime, but could treat absolute paths and MAST roots as, well, absolute references. The emulator currently does not track MAST roots at all, so that would be needed to have full compatibility, but would be a pretty simple thing to add.

Comment (greenhat) [reply codegen/masm/src/emulator/mod.rs:1552]: Thank you for the thorough explanation. Do you want me to implement it in this PR? I'd rather make an issue out of it and tackle it in a new PR.

**Comment by bitwalker** [comment]
@greenhat Is this ready to be merged now?

**Comment by greenhat** [comment]
Yes. I was waiting for your replay in https://github.com/0xPolygonMiden/compiler/pull/222#discussion_r1664197859 above regarding the emulator.

File: codegen/masm/src/emulator/mod.rs (hunk 1 above)
Comment (bitwalker) [reply codegen/masm/src/emulator/mod.rs:1552]: @greenhat That's fine by me
