### PR TITLE
fix: add symlink support in the new project template `cargo miden new`

### LINKED ISSUE #1002: Symlink support in the new project template in the `cargo miden new` command
`render_template` fails on symlink. Handle the symlink (re-create).

Restore the symlinks in the new project template removed in https://github.com/0xMiden/project-template/pull/22

### PR DESCRIPTION
**Pull request by greenhat**
Close #1002

### CODE REVIEW

File: tools/cargo-miden/src/template.rs [hunk 1]
```diff
@@ -273,6 +278,28 @@ fn render_template(
...
+    std::os::unix::fs::symlink(target, destination).with_context(|| {
+        format!("Failed to create symlink '{}' -> '{}'", destination.display(), target.display())
+    })?;
+    Ok(())
+}
+
+/// Creates a symlink at `destination` that points to `target`.
+#[cfg(not(unix))]
+fn create_symlink(_source: &Path, _target: &Path, _destination: &Path) -> Result<()> {
+    bail!("Template symlink recreation is only supported on Unix platforms")
```
Comment (bitwalker) [inline tools/cargo-miden/src/template.rs]: I would suggest we make a copy of the file on non-Unix targets, and maybe add a version for Windows that uses hardlinks - but we probably shouldn't support anything in templates that doesn't at least work on all targets where `cargo miden` may be run. We don't really properly support Windows at the moment (at least not intentionally), but we will need to eventually.

Comment (greenhat) [reply tools/cargo-miden/src/template.rs]: Sure. Done in 34ffc86581801b34260398ecab96fbec6c84a6b3
